### PR TITLE
Added __pycache__/ to .gitignore.  Fix typo

### PR DESCRIPTION
**Pull request by mwengren**
Also, added a potential fix to pre-commit GHA (TBD - @ocefpaf please take a look if this is correct)

### CODE REVIEW

**Comment by ocefpaf** [comment]
Thanks @mwengren!

BTW, I'm planning on changing master to main soon in this repo to be compliant with GitHub's new default.

**Comment by mwengren** [comment]
Ok, so some of the lines as in: https://github.com/ioos/ioos-python-package-skeleton/commit/b5045d9cfe83f788076d85e3b69c8e73909b7bf9#diff-ac5eead3f3ce4863c524fff031a87b7aecccb4a0493df087a4e1c704a1505036 aren't needed any more?  I'm wondering how I should update my downstream repo based on this skeleton.

**Comment by mwengren** [comment]
Also, regarding branch names, I was wondering if we should change the default branch to 'main' IOOS organization-wide, or if that might break things.  It looks like it only affects new repositories, so I guess it's safe to change...

**Comment by mwengren** [comment]
Ah, I think I see what happened with my PR.  I used `gh pr create` locally for the first time to create my PR and didn't see the commits I'd missed on the master branch.  Lesson learned I suppose for next time, should have caught that using the GitHub interface I think.

**Pull request merged**
